version: "3.9"

services:
  mysql:
    image: mysql:8.3
    container_name: cloudguard-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloudguard
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal

  backend:
    build: ./api
    container_name: cloudguard-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cloudguard
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - internal
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.cloudguardstage.com`)
      - traefik.http.routers.api.entrypoints=websecure
      - traefik.http.routers.api.tls.certresolver=le
      - traefik.http.services.api.loadbalancer.server.port=8080
    ports:
      - "8081:8080"

  frontend:
    build: ./frontend
    container_name: cloudguard-frontend
    depends_on:
      - backend
    networks:
      - internal
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.rule=Host(`app.cloudguardstage.com`)
      - traefik.http.routers.app.entrypoints=websecure
      - traefik.http.routers.app.tls.certresolver=le
      - traefik.http.services.app.loadbalancer.server.port=80
    ports:
      - "4200:80"

volumes:
  mysql_data:

networks:
  internal:
    driver: bridge
  traefik:
    external: true